apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-student-id-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-student-id-app
  template:
    metadata:
      labels:
        app: my-student-id-app
    spec:
      containers:
      - name: my-student-id-app
        image: lnso/my-student-id-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-student-id-app-service
spec:
  selector:
    app: my-student-id-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer